### ISSUE TITLE
第二章：数据清洗及特征处理 ——缺失值处理

### ISSUE THREAD

**Issue by binnhe** [datawhalechina/hands-on-data-analysis#4]
答案代码：
df[df['Age']==None]=0
**df.head(3)**
并不能看出前面处理结果

**Comment by andongBlue** [comment]
你好呀
教程里提供了多个方法来验证是否为无效值。对于None来说这里确实无法验证的到缺失值。原因是为什么呢？和其他给出的方法相比，造成的原因是什么呢？你可以自己先来搜搜。

这部分的详细解析，我会在下一次课程更新中详细给出。
